version: "3.5"
services:
  app:
    build: 
      context: .
    image: myzap:latest  
    container_name: myzap
    working_dir: /usr/src/app
    volumes:
      - ${MYZAP_SESSION_LOCAL}:/usr/src/app/tokens
    ports:
      - ${HOST_PORT}:${PORT}
    networks:
      backend:
        aliases:
          - myzap
networks:
  backend:
    name: myzap_network